<?php
declare(strict_types=1);

require_once __DIR__ . '/includes/bootstrap.php';
require_once __DIR__ . '/includes/csrf.php';
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/access-management.php';
require_once __DIR__ . '/includes/switchboard.php';

$user = require_login();
$role = strtolower((string) ($user['role'] ?? 'client'));
if (!in_array($role, ['admin', 'editor'], true)) { http_response_code(403); echo 'Only admins and editors can access Switchboard.'; exit; }
$displayName = trim((string) ($user['full_name'] ?: $user['email']));
$initials = strtoupper(substr($displayName, 0, 1));
$roleLabel = ucfirst($role);
$notice = $_SESSION['switchboard_notice'] ?? null;
$error = $_SESSION['switchboard_error'] ?? null;
unset($_SESSION['switchboard_notice'], $_SESSION['switchboard_error']);

function switchboard_flash_success(string $message): void { $_SESSION['switchboard_notice'] = $message; }
function switchboard_flash_error(string $message): void { $_SESSION['switchboard_error'] = $message; }
function switchboard_redirect(array $params = []): void { redirect_to('/switchboard' . ($params ? '?' . http_build_query($params) : '')); }
function switchboard_status_class(string $value): string { return strtolower(str_replace([' ', '/'], '-', $value)); }
function switchboard_display_date(?string $value): string { if (!$value) return 'No activity'; $time = strtotime($value); return $time ? date('M j, g:i A', $time) : $value; }
function switchboard_sidebar(string $roleLabel, string $role): void
{
    ob_start();
    access_sidebar('switchboard', $roleLabel, $role);
    $html = ob_get_clean();
    $insert = <<<'HTML'
<a class="is-active" href="/switchboard" aria-current="page"><span class="nav-icon" aria-hidden="true">S</span><span class="nav-label">Switchboard</span></a>
HTML;
    $pattern = <<<'REGEX'
/(<a class="[^"]*" href="\/carrier"[^>]*>.*?<span class="nav-label">Carrier<\/span><\/a>)/s
REGEX;
    $html = preg_replace($pattern, '$1' . $insert, $html, 1) ?? $html;
    $html = str_replace('<div class="sidebar-group " data-playground-group>', '<div class="sidebar-group is-open is-active" data-playground-group>', $html);
    $html = str_replace('data-playground-toggle aria-expanded="false"', 'data-playground-toggle aria-expanded="true"', $html);
    echo $html;
}

$pdo = null; $schemaReady = false; $schemaMessage = '';
try { $pdo = db(); switchboard_ensure_schema($pdo); $schemaReady = switchboard_schema_ready($pdo); } catch (Throwable $dbError) { error_log('Switchboard database unavailable: ' . $dbError->getMessage()); $schemaMessage = 'Switchboard cannot connect to the portal database yet. Check the database config or run /update.php after deployment.'; }

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!$pdo instanceof PDO || !$schemaReady) { switchboard_flash_error('Switchboard database tables are not ready. Log in as an admin and run /update.php after deployment.'); switchboard_redirect(); }
    if (!csrf_verify($_POST['csrf_token'] ?? null)) { switchboard_flash_error('Your session expired. Please refresh and try again.'); switchboard_redirect(); }
    $conversationId = switchboard_post_int('conversation_id');
    try {
        $action = switchboard_clean_text('action', 80);
        if ($action === 'create_conversation') {
            $title = switchboard_clean_text('title', 190); $contactName = switchboard_clean_text('participant_name', 190); $contactEmail = switchboard_clean_email('participant_email'); $contactPhone = switchboard_clean_text('participant_phone', 80); $initialMessage = switchboard_clean_text('initial_message', 12000); $assignedTo = switchboard_assignee_id($pdo, switchboard_post_int('assigned_to'));
            if ($title === '') throw new RuntimeException('Conversation title is required.');
            if ($contactName === '' && $contactEmail === '' && $contactPhone === '') throw new RuntimeException('Add at least one participant contact detail.');
            $pdo->beginTransaction();
            $pdo->prepare('INSERT INTO switchboard_conversations (title, conversation_type, status, priority, last_message_preview, last_message_at, assigned_to) VALUES (?, ?, ?, ?, ?, ?, ?)')->execute([$title, switchboard_type(switchboard_clean_text('conversation_type', 40, 'General')), switchboard_status(switchboard_clean_text('status', 40, 'Open')), switchboard_priority(switchboard_clean_text('priority', 40, 'Normal')), $initialMessage !== '' ? switchboard_preview($initialMessage) : '', $initialMessage !== '' ? gmdate('Y-m-d H:i:s') : null, $assignedTo]);
            $newId = (int) $pdo->lastInsertId();
            $participant = $pdo->prepare('INSERT INTO switchboard_participants (conversation_id, name, email, phone, role, is_internal, last_seen_at) VALUES (?, ?, ?, ?, ?, ?, ?)');
            $participant->execute([$newId, $contactName ?: ($contactEmail ?: 'External contact'), $contactEmail, $contactPhone, 'customer', 0, null]);
            $participant->execute([$newId, $displayName, (string) $user['email'], '', 'owner', 1, gmdate('Y-m-d H:i:s')]);
            if ($initialMessage !== '') $pdo->prepare('INSERT INTO switchboard_messages (conversation_id, sender_name, sender_email, sender_type, message_body, message_type, attachments, is_read, sent_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())')->execute([$newId, $displayName, (string) $user['email'], 'internal', $initialMessage, 'text', '', 1]);
            $pdo->commit(); switchboard_log_activity($pdo, (int) $user['id'], 'switchboard conversation created', $newId, $title); switchboard_flash_success('Conversation created.'); switchboard_redirect(['open' => $newId]);
        }
        if ($action === 'send_message') { switchboard_send_message($pdo, $conversationId, switchboard_clean_text('message_body', 12000), $user, 'internal'); switchboard_log_activity($pdo, (int) $user['id'], 'switchboard message sent', $conversationId); switchboard_flash_success('Message sent.'); switchboard_redirect(['open' => $conversationId]); }
        if ($action === 'update_conversation') { if ($conversationId <= 0 || !switchboard_fetch_conversation($pdo, $conversationId)) throw new RuntimeException('Choose a valid conversation.'); $title = switchboard_clean_text('title', 190); if ($title === '') throw new RuntimeException('Conversation title is required.'); $pdo->prepare('UPDATE switchboard_conversations SET title = ?, conversation_type = ?, status = ?, priority = ?, assigned_to = ?, updated_at = NOW() WHERE id = ?')->execute([$title, switchboard_type(switchboard_clean_text('conversation_type', 40, 'General')), switchboard_status(switchboard_clean_text('status', 40, 'Open')), switchboard_priority(switchboard_clean_text('priority', 40, 'Normal')), switchboard_assignee_id($pdo, switchboard_post_int('assigned_to')), $conversationId]); switchboard_flash_success('Conversation updated.'); switchboard_redirect(['open' => $conversationId]); }
        if (in_array($action, ['archive_conversation', 'delete_conversation', 'mark_conversation_read', 'mark_conversation_unread'], true)) { if ($conversationId <= 0 || !switchboard_fetch_conversation($pdo, $conversationId)) throw new RuntimeException('Choose a valid conversation.'); if ($action === 'delete_conversation') { $pdo->prepare('DELETE FROM switchboard_conversations WHERE id = ?')->execute([$conversationId]); switchboard_flash_success('Conversation deleted.'); switchboard_redirect(); } if ($action === 'archive_conversation') { $pdo->prepare("UPDATE switchboard_conversations SET status = 'Archived', updated_at = NOW() WHERE id = ?")->execute([$conversationId]); switchboard_flash_success('Conversation archived.'); } else { $isRead = $action === 'mark_conversation_read' ? 1 : 0; $pdo->prepare('UPDATE switchboard_messages SET is_read = ?, updated_at = NOW() WHERE conversation_id = ?')->execute([$isRead, $conversationId]); switchboard_flash_success($isRead ? 'Conversation marked as read.' : 'Conversation marked as unread.'); } switchboard_redirect(['open' => $conversationId]); }
        if (in_array($action, ['mark_message_read', 'mark_message_unread'], true)) { $messageId = switchboard_post_int('message_id'); if ($messageId <= 0) throw new RuntimeException('Choose a valid message.'); $isRead = $action === 'mark_message_read' ? 1 : 0; $pdo->prepare('UPDATE switchboard_messages SET is_read = ?, updated_at = NOW() WHERE id = ? AND conversation_id = ?')->execute([$isRead, $messageId, $conversationId]); switchboard_flash_success($isRead ? 'Message marked as read.' : 'Message marked as unread.'); switchboard_redirect(['open' => $conversationId]); }
        throw new RuntimeException('Choose a valid Switchboard action.');
    } catch (Throwable $postError) { if ($pdo instanceof PDO && $pdo->inTransaction()) $pdo->rollBack(); switchboard_flash_error($postError->getMessage()); switchboard_redirect($conversationId > 0 ? ['open' => $conversationId] : []); }
}

$statuses = switchboard_statuses(); $priorities = switchboard_priorities(); $types = switchboard_types(); $filter = strtolower(trim((string) ($_GET['filter'] ?? 'all'))); if (!in_array($filter, ['all','unread','open','pending','resolved','archived','assigned'], true)) $filter = 'all'; $search = trim((string) ($_GET['search'] ?? '')); $priorityFilter = trim((string) ($_GET['priority'] ?? '')); if (!in_array($priorityFilter, array_merge([''], $priorities), true)) $priorityFilter = ''; $openedId = filter_var($_GET['open'] ?? 0, FILTER_VALIDATE_INT) !== false ? (int) ($_GET['open'] ?? 0) : 0;
$conversations = []; $openedConversation = null; $messages = []; $participants = []; $assignees = []; $counts = ['all'=>0,'unread'=>0,'open'=>0,'pending'=>0,'resolved'=>0,'archived'=>0,'assigned'=>0];
if ($pdo instanceof PDO && $schemaReady) {
    $counts['all'] = (int) $pdo->query('SELECT COUNT(*) FROM switchboard_conversations')->fetchColumn(); $counts['unread'] = (int) $pdo->query('SELECT COUNT(DISTINCT conversation_id) FROM switchboard_messages WHERE is_read = 0')->fetchColumn(); $counts['open'] = (int) $pdo->query("SELECT COUNT(*) FROM switchboard_conversations WHERE status = 'Open'")->fetchColumn(); $counts['pending'] = (int) $pdo->query("SELECT COUNT(*) FROM switchboard_conversations WHERE status = 'Pending'")->fetchColumn(); $counts['resolved'] = (int) $pdo->query("SELECT COUNT(*) FROM switchboard_conversations WHERE status = 'Resolved'")->fetchColumn(); $counts['archived'] = (int) $pdo->query("SELECT COUNT(*) FROM switchboard_conversations WHERE status = 'Archived'")->fetchColumn(); $assignedCount = $pdo->prepare('SELECT COUNT(*) FROM switchboard_conversations WHERE assigned_to = ?'); $assignedCount->execute([(int) $user['id']]); $counts['assigned'] = (int) $assignedCount->fetchColumn(); $assignees = switchboard_manageable_users($pdo);
    $where = []; $params = []; if ($filter === 'unread') $where[] = 'EXISTS (SELECT 1 FROM switchboard_messages um WHERE um.conversation_id = c.id AND um.is_read = 0)'; if ($filter === 'open') $where[] = "c.status = 'Open'"; if ($filter === 'pending') $where[] = "c.status = 'Pending'"; if ($filter === 'resolved') $where[] = "c.status = 'Resolved'"; if ($filter === 'archived') $where[] = "c.status = 'Archived'"; if ($filter === 'assigned') { $where[] = 'c.assigned_to = ?'; $params[] = (int) $user['id']; } if ($priorityFilter !== '') { $where[] = 'c.priority = ?'; $params[] = $priorityFilter; } if ($search !== '') { $where[] = '(c.title LIKE ? OR EXISTS (SELECT 1 FROM switchboard_participants p WHERE p.conversation_id = c.id AND (p.name LIKE ? OR p.email LIKE ?)) OR EXISTS (SELECT 1 FROM switchboard_messages m WHERE m.conversation_id = c.id AND m.message_body LIKE ?))'; $like = '%' . $search . '%'; array_push($params, $like, $like, $like, $like); }
    $stmt = $pdo->prepare('SELECT c.*, u.full_name AS assignee_name, u.email AS assignee_email, (SELECT COUNT(*) FROM switchboard_messages m WHERE m.conversation_id = c.id AND m.is_read = 0) AS unread_count FROM switchboard_conversations c LEFT JOIN users u ON u.id = c.assigned_to' . ($where ? ' WHERE ' . implode(' AND ', $where) : '') . ' ORDER BY COALESCE(c.last_message_at, c.updated_at) DESC, c.id DESC LIMIT 120'); $stmt->execute($params); $conversations = $stmt->fetchAll(); if ($openedId > 0) $openedConversation = switchboard_fetch_conversation($pdo, $openedId); if (!$openedConversation && $conversations) $openedConversation = switchboard_fetch_conversation($pdo, (int) $conversations[0]['id']); if ($openedConversation) { $messages = switchboard_fetch_messages($pdo, (int) $openedConversation['id']); $participants = switchboard_fetch_participants($pdo, (int) $openedConversation['id']); }
}
$csrf = csrf_token();
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="robots" content="noindex"><title>Switchboard | Oligarchy Services</title><link rel="stylesheet" href="/assets/styles.css?v=20260618-service-icons"><link rel="stylesheet" href="/assets/dashboard.css?v=20260621-automation"><link rel="stylesheet" href="/assets/switchboard.css?v=20260702-dashboard-align"><script defer src="/assets/dashboard.js?v=20260630-switchboard"></script></head><body class="dashboard-body switchboard-body"><div class="dashboard-shell" data-dashboard-shell><?php switchboard_sidebar($roleLabel, $role); ?><div class="sidebar-backdrop" data-sidebar-backdrop></div><div class="dashboard-main switchboard-main"><header class="dashboard-topbar switchboard-topbar"><div class="topbar-left"><button class="mobile-menu" type="button" data-mobile-menu aria-controls="portal-sidebar" aria-expanded="false">☰</button><div><p class="eyebrow">Playground</p><h1 data-section-title>Switchboard</h1></div></div><div class="topbar-actions"><span class="role-pill"><?= e($roleLabel) ?></span><div class="user-chip" title="<?= e($user['email']) ?>"><span><?= e($initials) ?></span><div><strong><?= e($displayName) ?></strong><small><?= e($user['email']) ?></small></div></div><a class="logout-link" href="/logout.php">Log out</a></div></header><main class="switchboard-workspace"><?php if ($notice): ?><div class="dashboard-alert is-success" role="status"><?= e((string) $notice) ?></div><?php endif; ?><?php if ($error): ?><div class="dashboard-alert is-error" role="alert"><?= e((string) $error) ?></div><?php endif; ?><?php if (!$schemaReady): ?><div class="dashboard-alert is-error" role="alert"><?= e($schemaMessage ?: 'Switchboard tables are not ready. Run /update.php as an admin.') ?></div><?php endif; ?>
<section class="switchboard-shell" aria-label="Switchboard messaging center"><aside class="conversation-rail" aria-label="Conversation list"><a class="new-conversation-button" href="#new-conversation">New conversation</a><form class="switchboard-search" method="get" action="/switchboard"><label><span class="sr-only">Search conversations</span><input name="search" type="search" value="<?= e($search) ?>" placeholder="Search conversations"></label><select name="priority" aria-label="Filter by priority"><option value="">All priorities</option><?php foreach ($priorities as $priority): ?><option value="<?= e($priority) ?>" <?= $priorityFilter === $priority ? 'selected' : '' ?>><?= e($priority) ?></option><?php endforeach; ?></select><button class="button primary" type="submit">Search</button></form><nav class="switchboard-tabs" aria-label="Conversation filters"><?php foreach ([['all','All'],['unread','Unread'],['open','Open'],['pending','Pending'],['resolved','Resolved'],['archived','Archived'],['assigned','Assigned to Me']] as $tab): ?><a class="<?= $filter === $tab[0] ? 'is-active' : '' ?>" href="/switchboard?filter=<?= e($tab[0]) ?>"><span><?= e($tab[1]) ?></span><strong><?= e((string) $counts[$tab[0]]) ?></strong></a><?php endforeach; ?></nav><div class="conversation-list" role="list"><?php if (!$conversations): ?><p class="switchboard-empty">No conversations found.</p><?php endif; ?><?php foreach ($conversations as $conversation): ?><a class="conversation-card <?= (int) ($conversation['unread_count'] ?? 0) > 0 ? 'is-unread' : '' ?> <?= $openedConversation && (int) $openedConversation['id'] === (int) $conversation['id'] ? 'is-selected' : '' ?>" href="/switchboard?<?= e(http_build_query(array_filter(['filter'=>$filter,'search'=>$search,'priority'=>$priorityFilter,'open'=>(int) $conversation['id']], static fn($value) => $value !== ''))) ?>" role="listitem"><span class="conversation-avatar"><?= e(strtoupper(substr((string) $conversation['title'], 0, 1))) ?></span><span class="conversation-summary"><strong><?= e($conversation['title']) ?></strong><small><?= e($conversation['last_message_preview'] ?: 'No messages yet') ?></small><em><?= e((string) ($conversation['assignee_name'] ?: $conversation['assignee_email'] ?: 'Unassigned')) ?></em></span><span class="conversation-meta"><time><?= e(switchboard_display_date((string) ($conversation['last_message_at'] ?: $conversation['updated_at']))) ?></time><span class="status status-<?= e(switchboard_status_class((string) $conversation['status'])) ?>"><?= e($conversation['status']) ?></span><?php if ((int) ($conversation['unread_count'] ?? 0) > 0): ?><b><?= e((string) $conversation['unread_count']) ?></b><?php endif; ?></span></a><?php endforeach; ?></div></aside>
<section class="chat-panel" aria-label="Message thread"><?php if (!$openedConversation): ?><div class="chat-empty"><h2>Select a conversation</h2><p>Open a Switchboard conversation to view messages, contact details, and reply from the team inbox.</p></div><?php else: ?><header class="chat-header"><div><p class="eyebrow"><?= e($openedConversation['conversation_type']) ?> conversation</p><h2><?= e($openedConversation['title']) ?></h2><span><?= e((string) ($openedConversation['assignee_name'] ?: $openedConversation['assignee_email'] ?: 'Unassigned')) ?> · <?= e($openedConversation['priority']) ?> priority</span></div><div class="chat-actions"><span class="status status-<?= e(switchboard_status_class((string) $openedConversation['status'])) ?>"><?= e($openedConversation['status']) ?></span><a class="secondary-action" href="#edit-conversation">Edit</a></div></header><div class="message-thread" role="log" aria-label="Conversation messages"><?php if (!$messages): ?><p class="switchboard-empty">No messages yet.</p><?php endif; ?><?php foreach ($messages as $message): $isInternal = (string) $message['sender_type'] === 'internal'; ?><article class="message-row <?= $isInternal ? 'is-internal' : 'is-external' ?>"><div class="message-bubble"><div class="message-meta"><strong><?= e($message['sender_name']) ?></strong><span><?= e(switchboard_display_date((string) $message['sent_at'])) ?></span><?php if ((int) $message['is_read'] === 0): ?><em>Unread</em><?php endif; ?></div><p><?= nl2br(e((string) $message['message_body'])) ?></p><form method="post"><input type="hidden" name="csrf_token" value="<?= e($csrf) ?>"><input type="hidden" name="action" value="<?= (int) $message['is_read'] === 1 ? 'mark_message_unread' : 'mark_message_read' ?>"><input type="hidden" name="conversation_id" value="<?= e((string) $openedConversation['id']) ?>"><input type="hidden" name="message_id" value="<?= e((string) $message['id']) ?>"><button class="message-read-toggle" type="submit"><?= (int) $message['is_read'] === 1 ? 'Mark unread' : 'Mark read' ?></button></form></div></article><?php endforeach; ?></div><form class="message-composer" method="post"><input type="hidden" name="csrf_token" value="<?= e($csrf) ?>"><input type="hidden" name="action" value="send_message"><input type="hidden" name="conversation_id" value="<?= e((string) $openedConversation['id']) ?>"><label><span class="sr-only">Message</span><textarea name="message_body" rows="3" required placeholder="Write a reply..."></textarea></label><button class="button primary" type="submit">Send</button></form><?php endif; ?></section>
<aside class="details-panel" aria-label="Conversation details"><?php if (!$openedConversation): ?><div class="detail-empty"><h2>Details</h2><p>Contact and conversation context appears here.</p></div><?php else: ?><section class="detail-card"><h2>Conversation</h2><dl><div><dt>Status</dt><dd><?= e($openedConversation['status']) ?></dd></div><div><dt>Priority</dt><dd><?= e($openedConversation['priority']) ?></dd></div><div><dt>Last activity</dt><dd><?= e(switchboard_display_date((string) ($openedConversation['last_message_at'] ?: $openedConversation['updated_at']))) ?></dd></div><div><dt>Assigned</dt><dd><?= e((string) ($openedConversation['assignee_name'] ?: $openedConversation['assignee_email'] ?: 'Unassigned')) ?></dd></div></dl></section><section class="detail-card"><h2>Participants</h2><?php if (!$participants): ?><p>No participants saved.</p><?php else: ?><ul class="participant-list"><?php foreach ($participants as $participant): ?><li><span><?= e(strtoupper(substr((string) $participant['name'], 0, 1))) ?></span><div><strong><?= e($participant['name']) ?></strong><small><?= e($participant['email'] ?: $participant['phone'] ?: 'No contact detail') ?></small><em><?= (int) $participant['is_internal'] === 1 ? 'Internal' : 'External' ?> · <?= e($participant['role']) ?></em></div></li><?php endforeach; ?></ul><?php endif; ?></section><section class="detail-card action-card"><?php foreach ([['mark_conversation_read','Mark read'],['mark_conversation_unread','Mark unread'],['archive_conversation','Archive']] as $item): ?><form method="post"><input type="hidden" name="csrf_token" value="<?= e($csrf) ?>"><input type="hidden" name="conversation_id" value="<?= e((string) $openedConversation['id']) ?>"><input type="hidden" name="action" value="<?= e($item[0]) ?>"><button class="secondary-action" type="submit"><?= e($item[1]) ?></button></form><?php endforeach; ?><form method="post" data-confirm="Delete this conversation and all messages?"><input type="hidden" name="csrf_token" value="<?= e($csrf) ?>"><input type="hidden" name="conversation_id" value="<?= e((string) $openedConversation['id']) ?>"><input type="hidden" name="action" value="delete_conversation"><button class="table-action danger" type="submit">Delete</button></form></section><?php endif; ?></aside></section>
<section class="switchboard-modal" id="new-conversation" aria-labelledby="new-conversation-title"><a class="modal-close" href="/switchboard" aria-label="Close new conversation form">×</a><form class="switchboard-form" method="post"><input type="hidden" name="csrf_token" value="<?= e($csrf) ?>"><input type="hidden" name="action" value="create_conversation"><h2 id="new-conversation-title">New conversation</h2><div class="switchboard-form-grid"><label>Title<input name="title" maxlength="190" required placeholder="Account follow-up"></label><label>Type<select name="conversation_type"><?php foreach ($types as $type): ?><option value="<?= e($type) ?>"><?= e($type) ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><?php foreach ($statuses as $status): ?><option value="<?= e($status) ?>"><?= e($status) ?></option><?php endforeach; ?></select></label><label>Priority<select name="priority"><?php foreach ($priorities as $priority): ?><option value="<?= e($priority) ?>" <?= $priority === 'Normal' ? 'selected' : '' ?>><?= e($priority) ?></option><?php endforeach; ?></select></label><label>Participant name<input name="participant_name" maxlength="190" placeholder="Jordan Lee"></label><label>Participant email<input name="participant_email" type="email" maxlength="190" placeholder="jordan@example.com"></label><label>Participant phone<input name="participant_phone" maxlength="80" placeholder="(555) 010-0199"></label><label>Assigned to<select name="assigned_to"><option value="0">Unassigned</option><?php foreach ($assignees as $assignee): ?><option value="<?= e((string) $assignee['id']) ?>"><?= e((string) ($assignee['full_name'] ?: $assignee['email'])) ?></option><?php endforeach; ?></select></label><label class="wide-field">Initial message<textarea name="initial_message" rows="5" placeholder="Start the thread with the first note or customer message."></textarea></label></div><button class="button primary" type="submit">Create conversation</button></form></section>
<?php if ($openedConversation): ?><section class="switchboard-modal" id="edit-conversation" aria-labelledby="edit-conversation-title"><a class="modal-close" href="/switchboard?open=<?= e((string) $openedConversation['id']) ?>" aria-label="Close edit conversation form">×</a><form class="switchboard-form" method="post"><input type="hidden" name="csrf_token" value="<?= e($csrf) ?>"><input type="hidden" name="action" value="update_conversation"><input type="hidden" name="conversation_id" value="<?= e((string) $openedConversation['id']) ?>"><h2 id="edit-conversation-title">Edit conversation</h2><div class="switchboard-form-grid"><label>Title<input name="title" maxlength="190" required value="<?= e($openedConversation['title']) ?>"></label><label>Type<select name="conversation_type"><?php foreach ($types as $type): ?><option value="<?= e($type) ?>" <?= $openedConversation['conversation_type'] === $type ? 'selected' : '' ?>><?= e($type) ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><?php foreach ($statuses as $status): ?><option value="<?= e($status) ?>" <?= $openedConversation['status'] === $status ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select></label><label>Priority<select name="priority"><?php foreach ($priorities as $priority): ?><option value="<?= e($priority) ?>" <?= $openedConversation['priority'] === $priority ? 'selected' : '' ?>><?= e($priority) ?></option><?php endforeach; ?></select></label><label>Assigned to<select name="assigned_to"><option value="0">Unassigned</option><?php foreach ($assignees as $assignee): ?><option value="<?= e((string) $assignee['id']) ?>" <?= (int) ($openedConversation['assigned_to'] ?? 0) === (int) $assignee['id'] ? 'selected' : '' ?>><?= e((string) ($assignee['full_name'] ?: $assignee['email'])) ?></option><?php endforeach; ?></select></label></div><button class="button primary" type="submit">Save conversation</button></form></section><?php endif; ?></main></div></div></div></body></html>